"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Polish_1 = require("./Polish");
const CityName_1 = require("@civ-clone/core-civilization/CityName");
const CityNameRegistry_1 = require("@civ-clone/core-civilization/CityNameRegistry");
[
    'Warsaw',
    'Kraków',
    'Łódź',
    'Wrocław',
    'Poznań',
    'Gdańsk',
    'Szczecin',
    'Bydgoszcz',
    'Lublin',
    'Białystok',
    'Katowice Silesian',
    'Gdynia',
    'Częstochowa',
    'Radom',
    'Sosnowiec',
    'Toruń',
    'Kielce',
    'Rzeszów',
    'Gliwice',
    'Zabrze',
    'Olsztyn',
    'Bielsko-Biała',
    'Bytom',
    'Zielona Góra',
    'Rybnik',
    'Ruda Śląska',
    'Tychy',
    'Gorzów Wielkopolski',
    'Dąbrowa Górnicza',
    'Płock',
    'Elbląg',
    'Opole',
    'Wałbrzych',
    'Włocławek',
    'Tarnów',
    'Chorzów',
    'Kalisz',
    'Koszalin',
    'Legnica',
    'Grudziądz',
    'Słupsk',
    'Jaworzno',
    'Jastrzębie Zdrój',
    'Jelenia Góra',
    'Nowy Sącz',
    'Konin',
    'Piotrków Trybunalski',
    'Siedlce',
    'Lubin',
    'Inowrocław',
    'Mysłowice',
    'Piła',
    'Ostrowiec Świętokrzyski',
    'Ostrów Wielkopolski',
    'Siemianowice Śląskie',
    'Stargard',
    'Pabianice',
    'Gniezno',
    'Suwałki',
    'Głogów',
    'Chełm',
    'Przemyśl',
    'Zamość',
    'Tomaszów Mazowiecki',
    'Stalowa Wola',
    'Kędzierzyn-Koźle',
    'Leszno',
    'Łomża',
    'Żory',
    'Bełchatów',
    'Mielec',
    'Tarnowskie Góry',
    'Tczew',
    'Świdnica',
    'Piekary Śląskie',
    'Będzin',
    'Zgierz',
    'Biała Podlaska',
    'Racibórz',
    'Ełk',
    'Pruszków',
    'Świętochłowice',
    'Ostrołęka',
    'Starachowice',
    'Zawiercie',
    'Legionowo',
    'Tarnobrzeg',
    'Puławy',
    'Wodzisław Śląski',
    'Radomsko',
].forEach((name, i) => CityNameRegistry_1.instance.register(new CityName_1.default(name, Polish_1.default, i === 0)));
//# sourceMappingURL=registerCityNames.js.map